### ISSUE TITLE
[PD] Write your personal statement

### ISSUE THREAD

**Issue by kayali436** [kayali436/Coursework-Planner-CYF#10]
From Course-Fundamentals created by [kfklein15](https://github.com/kfklein15): CodeYourFuture/Course-Fundamentals#23  

### Coursework content

Write 1 paragraph of your personal story/statement

### Estimated time in hours

1

### What is the purpose of this assignment?

1. Write a 1 paragraph statement - between 50 and 100 words. Think about skills you have that can be used in your future job in tech, and mention them in this text.
2. Check grammar using [Grammarly](https://www.grammarly.com/) or a similar tool. 
3. Add your statement to the "Personal Statement" thread on the Cohort Slack channel. If the thread hasn’t been created yet, please do it. 

### How to submit

Add the link to your post on Slack on this coursework
Add a screenshot of your post on this coursework

### Anything else?

[This video](https://slack.com/intl/en-gb/help/articles/202528808-Search-in-Slack) explains how to search in Slack

**Comment by kayali436** [comment]
![Image](https://github.com/kayali436/Coursework-Planner-CYF/assets/79542167/35ae605a-b436-46f2-82db-aa31a1fe8876)

https://docs.google.com/document/d/1LS03XtqZJtRo7d6U5HnM-0yqOdFLu0gbaitb7nwPF6Q/edit?usp=sharing

**Comment by kfklein15** [comment]
This is a good personal statement. However, you talked more about why you want to become a developer instead of the assignment: " Think about _skills you have_ that can be used in your future job in tech". It's important to read and understand the assignment since your life will be about that once you become a developer.

AI checker: 40% of the text might have been written by AI. Not bad.
